name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests with coverage
        run: npm test -- --coverage

      - name: End-to-end tests
        run: xvfb-run -a npm run test:e2e

      - name: Build extension package
        run: npm run build

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: laserfocus-bundle
          path: laserfocus.zip 